spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:deneb
    username: sa
    password:
    name: deneb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true